### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by 100pcrack** [Steveice10/memchunkhax2#2]
I can't build the repo.
Lastest version of Devkitarm. Win7 x32

**Comment by ihaveamac** [comment]
I'm going to assume that you have an error relating to __sync_get_arbiter

you need to manually build the latest commit of libctru because the latest release (1.0.0) doesn't contain this pull request: https://github.com/smealum/ctrulib/pull/235

**Comment by 100pcrack** [comment]
How do I do that?

**Comment by Substance12** [comment]
Why do you want to do it? It doesn't work yet anyway.

**Comment by vlaridus** [comment]
You guys really can't wait for piracy, can you?

**Comment by ihaveamac** [comment]
in any case, you have no real purpose building it now.

**Comment by xfirm** [comment]
Maybe to test a commit before making a pull req?

**Comment by Substance12** [comment]
I for one am only waiting to play Cave Story 3D (impossible to find in my country) and emulators. But really, if this worked already people would be shitting themselves over at GBATemp. This. Does. Not. Work. Yet. Give steveice10 time. Rome wasn't built in one day.

**Comment by xfirm** [comment]
I want it because it means I can make applications that use kernel permissions and install homebrew to homescreen....

**Comment by ihaveamac** [comment]
you can't use this for kernel hax or downgrading yet.

anyway you could say this issue is solved: build the latest libctru, edit the Makefile to point to it, and then build this. frankly if you can't figure that out then should you really be messing with this? ;)

**Comment by Substance12** [comment]
Was this even an issue? Troll can't read, thinks he can downgrade already with unfinished code...

**Comment by xfirm** [comment]
i know you cannot yet but when it is done you can... yeah this should be marked as solved

**Comment by s3r1alpari4h** [comment]
You cant build with Windows ;)

**Comment by s3r1alpari4h** [comment]
Insta Linux bruh
