### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by TeToNN** [Steveice10/memchunkhax2#3]
Are you sure the memory is currently correctly mapped after you switch the pointer?

Since
```
 MemChunkHdr* fakeHdr = (MemChunkHdr*) &timerObj->timerEnabled;
```
does 
```
fakeHdr->size > 0 ?
```
The memory won't be mapped otherwise,  according to derrek's re
Probably need to use the attributes you can change (interval/initial)

(And yes the next pointer should probably be NULL)

PS : I might be talking nonsence (It's highly possible)

**Comment by delebile** [comment]
That's a point.
I also tried to set the interval/initial so that it could find free pages and a NULL as "next" pointer, but it didn't work; it succeedes svcControlMemory execution but it doesn't run the payload function.
I reversed svcCreateTimer I came out with the doubt that r1 doesnt actually contain the KTimer object ptr at the end of the svc call. 
I can be wrong though.

**Comment by TeToNN** [comment]
The address of the KTimer object seems decent to me.
The problem I encounter is everytime i use 
```
svcSetTimer(timer, 0, 0);
```
with the interval argument different of 0, the code crashes before the mapping ends

Example
```
svcSetTimer(timer, 0, 1);
KTimer* timerObj = (KTimer*) (timerAddr - 4);
//start chunk at correct offset for size = 1, next = NULL, prev  = NULL
MemChunkHdr* fakeHdr = (MemChunkHdr*) &timerObj->interval + 2;
```

I do believe there might be a problem with svcSetTimer

**Comment by delebile** [comment]
I looked better at my disassebly and i probably was wrong, the KObjects is legit.
I'm gonna experiment with all the values i can.

**Comment by Steveice10** [comment]
svcSetTimer was broken in ctrulib. You will need to update to the latest source commit.

Basically, I'm pointing it at the field "Timer Enabled". This field is mostly set to 1 (unless you cancel the timer I believe), and its subsequent 3 bytes are always 0 if you create the timer with reset type 0. Therefore, it forms a size field of 1. The interval field can then be used to set next and prev values. I may need to set them to non-zero, or something else entirely may be broken.

**Comment by TeToNN** [comment]
I have the last ctrulib though.
Is the timer enabled if you get the interval and initial to 0 though?

I just managed to make the mapping work (at least it doesnt crash), by setting the reset type to 1 and having the memchunk start at suspendtime +6 (so that size is 1)

**Comment by Steveice10** [comment]
From my memory dumps, yes, that should result in timer enabled = 1, reset mode = 0, unused = 0, interval = 0.

**Comment by TeToNN** [comment]
Alright then, didn"t have access to these informations, my bad :)

**Comment by TuxSH** [comment]
Crashes soon after  printf("Final control result: 0x%08X\n", (int) control_res);
Using the latest commit, latest ctrulib, O3DS xl 10.1-27E.

**Comment by Steveice10** [comment]
Yeah, the thing is not entirely complete or working yet, it's mainly groundwork for what needs to be done.

**Comment by TeToNN** [comment]
Pretty sure that's normal the code is still a WIP.

I guess now if the memory maping works correctly, a second KObject is needed in order to rewrite the vtable from the userspace (since the 1st timer vtable isnt accessible since it's before the memchunk) ?

**Comment by delebile** [comment]
That was what i thought too, in fact i keep trying to creating other kTimers after the first.
There are some things i am not sure about, like : 
* Need the fake memchunkhdr to be page-aligned?
* If not, does the page allocation get aligned?
I just cannot dump AXIWRAM on my firmware.

**Comment by TeToNN** [comment]
The reason I thought the mapping didnt work is that even when creating new KTimers, dumping the two mapped pages (from userspace) always gives 0's while it's supposed to map the slabheap

**Comment by delebile** [comment]
The memory allocated is cleared, it's also written in derrek's pseudocode, and that's also the problem that makes this operation "delicate".
![vlcsnap-2015-12-28-19h13m07s261](https://cloud.githubusercontent.com/assets/13836700/12054855/56123f18-af27-11e5-8d3d-37188d48fadc.png)

**Comment by TeToNN** [comment]
Yeah I know.
But once the allocation is done, shouldnt the mapped memory act as a shared memory between kernel and userspace ? Hence creating new KTimer after allocation should be reflected in the userspace copy of the slabheap ?
That or I'm lost

**Comment by delebile** [comment]
Oh, that should be correct. 
You should also consider that wiping out all that area corrupts some other KObjects too (even if uninitialized) and the fake one too, and this can cause an error creating new ones. 
That's just my opinion...

**Comment by TeToNN** [comment]
Yeah lots of stuff to test :)

**Comment by delebile** [comment]
Pointing to the "Timer Enabled" field just do not work here, don't know why (OLD3DS 10.3E).
svcControlMemory returns 0 as supposed by pointing to timerObj->refCount to me, did anyone try?

Also, how are you sure of this address? 
``` 
void*** vtablePtr = (void***) (memAddr + PAGE_SIZE + ((u32) timerObj - ((u32) timerObj & ~0xFFF)));
```
Can't the error be here, or are you sure (I'm asking, since you have some memdumps)?
Becouse, if we understand well, we only need to properly overwrite the vtable pointer at this rate.

**Comment by Steveice10** [comment]
@delebile I believe I'm calculating that address right, and even if it is wrong, that isn't the issue here, as it isn't making it to that point.

**Comment by TeToNN** [comment]
Anyways you still need another kernel object located after the first timer, and replace his vtable, since the vtable of the timer isn't accessible from userspace (as the mapping starts at the fake memchunkhdr).

I don't know if you must do the vtable switching and closing handle in the small interval of time between mapping and clearing though

**Comment by shubshub** [comment]
So... I assume this is almost working now? Just curious
